rock = [
    {'banda': 'Deftones','follow': 81},
    {'banda': 'Audioslave','follow': 87},
    {'banda': 'Radiohead','follow': 103},
    {'banda': 'Metallica','follow': 250},
    {'banda': 'Megadeth','follow': 250},
    {'banda': 'Avenged Sevenfold','follow': 180},
    {'banda': 'Queen','follow': 200},
    {'banda': 'Iron maiden','follow': 195},
    {'banda': 'Silverchair','follow': 52},
    {'banda': 'Slipknot','follow': 505 },
    {'banda': 'Linkin Park','follow': 540},
    {'banda': 'Foo Fighters','follow': 76},
    {'banda': 'Skillet','follow': 78 },
    {'banda': 'The Beatles', 'follow': 610},
    {'banda': 'The Rolling Stones', 'follow': 430},
    {'banda': 'Nirvana', 'follow': 390},
    {'banda': 'Green Day', 'follow': 370},
    {'banda': 'AC/DC', 'follow': 520},
    {'banda': 'Red Hot Chili Peppers', 'follow': 490},
    {'banda': 'The Killers', 'follow': 210},
    {'banda': 'Muse', 'follow': 220},
    {'banda': 'Pearl Jam', 'follow': 180},
    {'banda': 'The Strokes', 'follow': 145},
    {'banda': 'System of a Down', 'follow': 310},
    {'banda': 'Panic! at the Disco', 'follow': 280},
    {'banda': 'Bring Me The Horizon', 'follow': 200},
    {'banda': 'Paramore', 'follow': 230},
    {'banda': 'My Chemical Romance', 'follow': 260},
    {'banda': 'The Smashing Pumpkins', 'follow': 130},
    {'banda': 'Imagine Dragons', 'follow': 650},
    {'banda': 'Evanescence', 'follow': 215},
    {'banda': 'Korn', 'follow': 195},
    {'banda': 'Arctic Monkeys', 'follow': 310},
    {'banda': 'U2', 'follow': 360},
    {'banda': 'Bon Jovi', 'follow': 285},
    {'banda': 'Guns N\' Roses', 'follow': 510},
    {'banda': 'The Offspring', 'follow': 170},
    {'banda': '30 Seconds to Mars', 'follow': 190},
    {'banda': 'Rammstein', 'follow': 200},
    {'banda': 'Creed', 'follow': 88},
    {'banda': 'Queens of the Stone Age', 'follow': 155},
    {'banda': 'The White Stripes', 'follow': 140},
    {'banda': 'Blink-182', 'follow': 275},
    {'banda': 'The Who', 'follow': 320},
    {'banda': 'Yes', 'follow': 120},
    {'banda': 'Led Zeppelin', 'follow': 500},
    {'banda': 'Deep Purple', 'follow': 190},
    {'banda': 'The Doors', 'follow': 220},
    {'banda': 'Nine Inch Nails', 'follow': 125},
    {'banda': 'Soundgarden', 'follow': 165},
    {'banda': 'Faith No More', 'follow': 110},
    {'banda': 'Alice in Chains', 'follow': 180},
    {'banda': 'Bullet for My Valentine', 'follow': 145}
]